### ISSUE TITLE
No unique fragment ends for capture length

### ISSUE THREAD

**Issue by WanyingX** [deLaatLab/pipe4C#23]
Hi,

I was running one 4C data but got this issue which no one had posted it before. I am confused by this problem because I have passed TRIM and MAPPING process but fail at this area. Could anyone share some insights?

![4C-seq issue](https://user-images.githubusercontent.com/52838412/175077022-744d3bff-edce-4d08-afac-9b85f18b4ac5.png)

Thanks

**Comment by krijgerp** [comment]
Dear Wanying Xu,
Have a look at https://github.com/deLaatLab/pipe4C/issues/21, possibly this is caused by a corrupt frag genome file. can you try deleting the mm10_CATG_GATC.rds file and try it again. Also, could you send me this file (mailto:delaatbioinf@hubrecht.eu), I will try to make a workaround for this in the future.

best,
Peter
