### ISSUE TITLE
Suggestions on long-range interaction

### ISSUE THREAD

**Issue by smartgamer** [deLaatLab/pipe4C#3]
I run the pipeline but it doesn't give any data on long-range interaction analysis.

Do you have any suggestions on which R packages or command-line tools to do downstream analysis for long-range interactions?

**Comment by krijgerp** [comment]
Dear smartgamer,
An R script to identify far-cis and trans contacts can be found in Splinter et al. [methods 2012]. In contrast to near-cis contacts, far-cis and trans contacts are sparse, are likely to originate from a single ligation event and are therefore binarized (>1 reads per fragment end is set to 1) to avoid possible PCR artifacts to influence results. Enrichment of contacts in a local window of fragment ends w is quantified with respect to a larger window W. A null model for this enrichment statistic is obtained by permutation of the reads and an FDR threshold is computed from the distribution of z-score normalized values of the statistic in the permuted samples. This normalization assumes that the total number of captures within each window w follows a binomial distribution, with success probability p determined by the total number of covered fragments in W. For far-cis analysis, window sizes of w = 100 and W = 3000 are recommended when using HindIII as the primary RE, but should be adjusted when using enzymes recognizing 4 bp motifs to reach similar genomic size bins. For trans contacts, a very similar method is used, but since trans contacts are even more rare, larger window sizes are required.
