### ISSUE TITLE
doPeakC does not exist

### ISSUE THREAD

**Issue by tamerbio** [deLaatLab/pipe4C#6]
Hi everyone,
I am using the following command to call peaks:
`resPeakC <- doPeakC(rdsFiles = rdsFiles)`

but it seems that there no such function  `doPeakC` at all!!
any idea?
best
TA

**Comment by krijgerp** [comment]
Dear TA,
The doPeakC function is present in the functions.R file.
I just checked the latest version present on Github together with our step-by-step tutorial and it should work. Could you indicate the exact error. Are you using the example data?

**Comment by tamerbio** [comment]
```
> setwd("/test/RDS")
> rdsFiles <- c("s1.rds", "s2.rds")
> resPeakC <- doPeakC(rdsFiles = rdsFiles)
Error in doPeakC(rdsFiles = rdsFiles) : could not find function "doPeakC"
```

**Comment by tamerbio** [comment]
```
> library(peakC)
> pipe4CFunctionsFile <- "functions.R"
> source(pipe4CFunctionsFile)
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'functions.R': No such file or directory
```

**Comment by geertgeeven** [comment]
Dear TA, you need to specify the full path to the pipe4CFunctionsFile. If
you navigate for instance to the folder /test/RDS first,
with setwd("/test/RDS"), and then type pipe4CFunctionsFile <-
"functions.R", this will not work, because functions.R file is not located
in /test/RDS/, so you need to write pipe4CFunctionsFile <- "<path to
pipe4C>/functions.R", e.g.  pipe4CFunctionsFile <-
"/home/TA/github/pipe4C/functions.R" if you cloned the pipe4C repository in
/home/TA/github/pipe4C/. Hope this helps !
